[package]
name = "text_adv"
version = "0.1.0"
authors = ["Pawel82S <theoptimizersgroup@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
console_engine = "1.5"
